#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Rin Hanaoka <s23c1110vk@s.chibakoudai.jp>

import sys

def get_divisors(num):
    ans = []
    for i in range(1,num+1):
        if num % i == 0:
            ans.append(i)
    return ans

if len(sys.argv) != 2:
    print("引数の数が多すぎます")
    sys.exit(1)

input_num = int(sys.argv[1])

if input_num < 0:
    print("負の数は入力できません")
    sys.exit(1)
else:
    print(get_divisors(input_num))

